let a=10;
let b=3;
console.log("a=",a,"&b=",b);
console.log("a+b=",a+b);
console.log("a-b=",a-b);
console.log("a*b=",a*b);
console.log("a/b=",a/b);
console.log("a%b=",a%b);
console.log("a**b=",a+b);
console.log("Assign operator");
let x=10;
console.log("x=",x);
console.log("x-=1",x=x-1);
console.log("x+=1",x=x+1);
console.log("x*=1",x=x*1);
console.log("x/=1",x/=2);
console.log("x%=1",x%=3);
console.log("x**=1",x**=1);
console.log("unary operator");
console.log("a=",a,"&b=",b);
console.log("++a=",++a);
console.log("a++=",a=a+1);
console.log("--=",--a);
console.log("a--=",a--);
let age=20;
let newage=age+1;
newage=++age;
console.log("relational operator");
let c=10;
let d=8;
console.log("c=",c,"&d=",d);
console.log("c>d=",c>d);
console.log("c<d=",c<d);
console.log("c>=d",c>=d);
console.log("c<=d",c<=d);
console.log("c==d",c==d);
console.log("c!=d",c!=d);
console.log("stric operator === it is know the data property");
let num=10;
let str="10";
console.log(num==str);
console.log(num===str);
console.log("1"===1);
console.log("4"===4);
// console.log(nul==undefined);
// console.log(null===undefined);
console.log("logical operator");
let  cond1=a>b;
let cond2=a<b;
console.log("cond1&&cond2=",cond1 && cond2);
console.log(a>b && a>b);
console.log(a<b && a<b);
console.log("condf1||cond2=",cond1||cond2);
console.log(a>b || a>b);
console.log(a<b || a<b);
console.log(a<b || a>b);
console.log("!a>b",!cond1);
console.log(!cond2);