let name="tone stark";
let role='iron man';
let a='a';
let num="10";
let empty=" ";
console.log(typeof name);
console.log(typeof role);
console.log(typeof a);
console.log(typeof num);
console.log(typeof empty);
let str="TONYSTARK";
console.log(str);
console.log(str[0]);
console.log(str[1]);
console.log(str.length);
console.log(str[str.length-1]);
let str1=10;
let str2=20;
let output=str1+str2;
console.log(output);
console.log("the out put is:" + (str1+str2));
let literals=`the output is ${str1+str2}`;
console.log(literals);
console.log(`total cal ${str1+str2}`);
