let str="hello";
let str2="world";
console.log(str.concat(str2));
console.log(str2.concat(str));
console.log(str.toLowerCase());
console.log(str.toUpperCase());
console.log(str.indexOf("h"));
console.log(str.indexOf("z"));
console.log(str.charAt(1));
console.log(str.repeat(4));
console.log(str.startsWith("h"));
console.log(str.endsWith("o"));
console.log(str.includes("h"));
console.log(str.replace("lo","p"));
console.log(str.substring(1));
console.log(str.substring(1,4));
console.log(str.slice(2));
console.log(str.slice(0,3));;
console.log(str.length);
console.log(str[0]);
console.log(str.split());
console.log("     hello".trim());
console.log("     hello".trimStart());
console.log("hello   ".trimEnd());
